### PR TITLE
This commit fixes #4

### LINKED ISSUE #4: Link color is not reflected on the bookmarks page.
image

### PR DESCRIPTION
**Pull request by amitvadhel**
Fixes for link color at bookmark page.

### CODE REVIEW

**Comment by antoviaque** [comment]
@amitvadhel Thank you for your contribution! :)

We will have a look at this - @kaizoku @mtyaka @xitij2000 @pkulkark Can one of you have a look at this as part of the community role?

Note that there is a pending PR from @lgp171188 at https://github.com/open-craft/edx-simple-theme/pull/2 - I'm not sure why it hasn't been merged yet, and he's off this week.

**Comment by mtyaka** [comment]
Thanks @amitvadhel! I'll take a look in the next couple of days.

**Comment by mtyaka** [comment]
This works well! I set it up on https://mtyaka.stage.opencraft.hosting/ :+1:

Screenshot 2020-05-14 at 08 29 23

We might want to hold off from merging until @lgp171188 updates us on the status of #2 though.

- [x] I tested this: I verified that the links on the bookmarks page now use the theme color.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ]  ~~Includes documentation~~

**Comment by lgp171188** [comment]
@mtyaka, I have closed the PR #2 (cf. [comment](https://github.com/open-craft/edx-simple-theme/pull/2#issuecomment-628134589)). So this can be merged.

**Comment by mtyaka** [comment]
@lgp171188 thanks for the update and @amitvadhel thanks for the contribution :)

**Pull request merged**
